services:
  backend:
    build:
      context: .
      dockerfile: ./apps/backend/Dockerfile.dev
    volumes:
      - ./apps/backend:/app/apps/backend
      - ./packages:/app/packages
      - ./pnpm-workspace.yaml:/app/pnpm-workspace.yaml:ro
      - ./package.json:/app/package.json:ro
      - ./pnpm-lock.yaml:/app/pnpm-lock.yaml:ro
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development
