services:
  backend:
    build:
      context: .
      dockerfile: ./apps/backend/Dockerfile.dev
    volumes:
      - ./apps/backend:/app/apps/backend
      - ./packages:/app/packages
      - ./pnpm-workspace.yaml:/app/pnpm-workspace.yaml:ro
      - ./package.json:/app/package.json:ro
      - ./pnpm-lock.yaml:/app/pnpm-lock.yaml:ro
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development
    networks:
      - trading-network

  database:
    image: timescale/timescaledb-ha:pg17
    restart: unless-stopped
    environment:
      POSTGRES_USER: "${DATABASE_USERNAME}"
      POSTGRES_PASSWORD: "${DATABASE_PASSWORD}"
      POSTGRES_DB: "${DATABASE_NAME}"
      TZ: "UTC"
    ports:
      - "${DOCKER_DATABASE_PORT}:5432"
    volumes:
      - ./.docker/timescaledb_data:/var/lib/postgresql/data
    networks:
      - trading-network
networks:
  trading-network:
    driver: bridge
