FROM node:20-alpine AS base
RUN apk add --no-cache libc6-compat

RUN corepack enable && corepack prepare pnpm@latest --activate

WORKDIR /app

COPY ./out/json/package.json .
COPY ./out/json/pnpm-lock.yaml .

COPY ./out/full/ .

RUN pnpm install --no-frozen-lockfile --prod=false

EXPOSE 3000

CMD ["pnpm", "run", "dev"]



